### ISSUE TITLE
Update spec to be separate from implementation

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/web5-spec#1]

**Comment by mistermoe** [comment]
Can you provide some context here @decentralgabe ?

**Comment by decentralgabe** [comment]
Idea was to have a clear specification defined for what features the SDK has - with links, descriptions, etc. This can be versioned.

separately we have an implementation report (test vectors, compliant sdks), with releases that comply with the spec versions.

**Comment by decentralgabe** [comment]
this is similar to how it's done in the w3c, e.g.:

- spec: https://w3c.github.io/vc-data-model/
- test suite: https://w3c.github.io/vc-data-model-2.0-test-suite/
