### ISSUE TITLE
Produce test vectors for `did:dht`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/web5-spec#11]
Produce language agnostic test vectors that can be used by each implementation to ensure that the following features work correctly:
* Creation
* Resolution

It may make sense for these vectors to live alongside the `did:dht` spec in the repo thats in

Related: #17

**Comment by decentralgabe** [comment]
related to https://github.com/TBD54566975/did-dht-method/issues/37

**Comment by decentralgabe** [comment]
test vectors are available here https://did-dht.com/#test-vectors need to be uptaken by this repo

**Comment by decentralgabe** [comment]
@nitro-neal are you able to help uptake the vectors here?

**Comment by andresuribe87** [comment]
Just noting that I added some test vectors, and updated the implementation, in https://github.com/TBD54566975/web5-kt/pull/181

**Comment by decentralgabe** [comment]
bumping this [after Adam's comment](https://github.com/TBD54566975/web5-swift/pull/15#discussion_r1492556338) that these are out of date with the spec

**Comment by decentralgabe** [comment]
closing as a dupe of #167
