### ISSUE TITLE
Move / dedupe presentation exchange test vectors in web5-kt

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/web5-spec#129]
we have quite a few test vectors for presentation exchange sitting in web5-kt's `resources` folder that we should move to web5-spec submodule. 

this will help test the other web5 sdk's against the edge cases laid out in these test vectors, and serve as a start of discussion when a test vector tests fails in one web5-sdk but passes in another web5-sdk.

**Comment by decentralgabe** [comment]
@jiyoontbd can we close this as a dupe of #171 ?

**Comment by jiyoontbd** [comment]
yea just edited the post in #171 ! closing
