### ISSUE TITLE
Write a spec for JWT

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/web5-spec#145]
Document decision around JWT including `misc` claim, for example

related issue: https://github.com/TBD54566975/web5-spec/issues/143

**Comment by decentralgabe** [comment]
what would our spec for JWT specify? we should be using tooling that follows the JWT RFCs

related to my thoughts in #144

**Comment by decentralgabe** [comment]
@jiyoontbd can this be closed?

**Comment by jiyoontbd** [comment]
maybe spec isn't the right word, but i wanted to document _somewhere_ that we marshal and unmarshal claims that are not part of the JWT RFC into / out of `misc`.

but maybe that's an internal detail that doesn't actually need to surface.

**Comment by decentralgabe** [comment]
this should be surfaced through uptake of specific JWT usage (e.g. in a VC)

if we have broader JWT usage and this comes up...we need to add that to the spec, probably just a pointer to use [Private Claims](https://datatracker.ietf.org/doc/html/rfc7519#section-4.3).
