### ISSUE TITLE
Granular error checking during vcJwt verify call

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-spec#147]
We need to have an ability to check which error happened in our test vectors, only having `errors:true` could lead to false positives, eg its failing for a different reason than you think

instead of having error messages in our test vector:

```
      "errorMessage":{
        "web5-js":"Verification failed: Malformed JWT. expected 3 parts. got 2",
        "web5-kt":"Malformed JWT. Expected 3 parts, got 2"
     }
```

Lets come up with a new way to have more grainular error testing. Probably something like this:

```
   "errorType": "InvalidSignature"
   ```
   
more context here - https://github.com/TBD54566975/web5-spec/pull/146

**Comment by jiyoontbd** [comment]
Also consider adding unit tests that check error messages, without depending on test vectors to tell you the expected error message

**Comment by decentralgabe** [comment]
@nitro-neal can we close this as dupe of #168 ?
Please make sure this case is covered in there
