### ISSUE TITLE
Add select credentials test vector with multiple Fields

### ISSUE THREAD

**Issue by tomdaffurn** [TBD54566975/web5-spec#158]
In the test vectors for the Presentation Exchange "select credentials" feature, no test case has an _Input Descriptor_ with more than one _Field_.
[test-vectors/presentation_exchange/select_credentials.json](https://github.com/TBD54566975/web5-spec/blob/main/test-vectors/presentation_exchange/select_credentials.json)

Add a new test vector that has an Input Descriptor with multiple Fields.

This is necessary to demonstrate a [bug in the web5-go implementation of SelectCredentials](https://github.com/TBD54566975/web5-go/issues/153). It might also be present in other language SDKs. 

It will also exercise the AND relationship of multiples Fields in an InputDescriptor

**Comment by decentralgabe** [comment]
related to #171
