### ISSUE TITLE
Clarify "DID Document & Resolution Validation"

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-spec#28]
Can clarification be provided for this set of SDK requirements:

<img width="486" alt="Screenshot 2023-11-09 at 12 00 49 PM" src="https://github.com/TBD54566975/sdk-development/assets/134693/f1ec5640-e126-4be4-9e2c-3c7f1f6d8be4">

**Comment by mistermoe** [comment]
apologies for the lack of clarity @frankhinek. This feature would've been better off surfacing as an issue in this repo first

## Common Error
The idea behind this was to scrub through our existing implementations to ensure that our `resolve` implementations were using the errors defined in [DID specification registries](https://www.w3.org/TR/did-spec-registries/#error) for [`didResolutionMetadata.error`](https://www.w3.org/TR/did-spec-registries/#error) 

<img width="1064" alt="image" src="https://github.com/TBD54566975/sdk-development/assets/4887440/2cab7c1a-50c9-4265-9ce0-98dd547eacfb">

## Json Schema
Usage of common errors led me to consider whether it'd be worthwhile to produce a JSON schema that could be used across all of our SDKs to validate did documents and did resolution results 

thoughts on whether either is worth the time?

**Comment by frankhinek** [comment]
No worries and thanks for the additional insight.  Agreed on supporting error reporting during DID resolution.  A few error types are included (`invalidDid` and `methodNotSupported`) were included in the JS [`DidResolver`](https://github.com/TBD54566975/web5-js/blob/main/packages/dids/src/did-resolver.ts), but we ought to have a consistent set of error codes across SDKs.  At a minimum we should support all of the _required_ error codes.

I haven't completed an exhaustive search but didn't turn up an existing JSON schema published for DID documents / DID resolution results.  It seems like consistent test vectors ought to be the higher priority and then address JSON schema validation if there's value to be gained.
